# Configure main menu and social menu


[[social]]
identifier = "RSS"
name = "RSS"
url = "/index.xml"

[social.params]
icon = "rss"

[[social]]
identifier = "telegram"
name = "telegram"
url = "https://t.me/NEXISTS"

[social.params]
icon = "telegram"

[[social]]
identifier = "bangumi"
name = "bangumi"
url = "https://bangumi.tv/user/nonexistentx"

[social.params]
icon = "bangumi"
